
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEABRE = 44;
  public static final int RESERVADA_TRUE = 29;
  public static final int DOSPUNTOS = 58;
  public static final int RESERVADA_SWITCH = 57;
  public static final int SIGNOIGUALIGUAL = 11;
  public static final int CHARR = 52;
  public static final int PARENTESISCIERRA = 3;
  public static final int PUNTOYCOMA = 4;
  public static final int RESERVADA_VOID = 32;
  public static final int ENTERO = 49;
  public static final int SIGNOIGUAL = 20;
  public static final int RESERVADA_DO = 56;
  public static final int RESERVADA_ELSE = 37;
  public static final int RESERVADA_DEFAULT = 60;
  public static final int RESERVADA_STRING = 31;
  public static final int SIGNODIVISION = 16;
  public static final int PARENTESISABRE = 2;
  public static final int RESERVADA_BREAK = 41;
  public static final int SIGNOMAS = 14;
  public static final int SIGNOMENOS = 15;
  public static final int SIGNOCOMA = 21;
  public static final int SIGNOMENOR = 8;
  public static final int ID = 50;
  public static final int RESERVADA_CONSOLE = 35;
  public static final int RESERVADA_WHILE = 40;
  public static final int SIGNOPOR = 13;
  public static final int EOF = 0;
  public static final int SIGNOMAYOR = 7;
  public static final int LLAVEABRE = 5;
  public static final int error = 1;
  public static final int LLAVECIERRA = 6;
  public static final int CADENA = 53;
  public static final int RESERVADA_INT = 25;
  public static final int SIGNOPUNTO = 12;
  public static final int RESERVADA_CHAR = 27;
  public static final int RESERVADA_FOR = 39;
  public static final int SIGNOMENORIGUAL = 10;
  public static final int RESERVADA_DOUBLE = 26;
  public static final int SIGNODIFERENTE = 22;
  public static final int DECIMALES = 51;
  public static final int RESERVADA_IF = 34;
  public static final int RESERVADA_FALSE = 30;
  public static final int RESERVADA_CASE = 59;
  public static final int SIGNOOR = 18;
  public static final int SIGNONOT = 19;
  public static final int SIGNOAND = 17;
  public static final int SIGNOINCREMENTO = 23;
  public static final int RESERVADA_DEFINIRG = 38;
  public static final int RESERVADA_TITULOY = 47;
  public static final int RESERVADA_TITULOX = 46;
  public static final int CORCHETECIERRA = 45;
  public static final int SIGNOMAYORIGUAL = 9;
  public static final int RESERVADA_TITULO = 48;
  public static final int RESERVADA_EJEX = 55;
  public static final int RESERVADA_BOOL = 28;
  public static final int RESERVADA_NEWVALOR = 42;
  public static final int RESERVADA_MAIN = 33;
  public static final int DOLAR = 24;
  public static final int RESERVADA_WRITE = 36;
  public static final int RESERVADA_GRAFICARPIE = 61;
  public static final int RESERVADA_VALORES = 54;
  public static final int RESERVADA_GRAFICARBARRAS = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "PUNTOYCOMA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "SIGNOMAYOR",
  "SIGNOMENOR",
  "SIGNOMAYORIGUAL",
  "SIGNOMENORIGUAL",
  "SIGNOIGUALIGUAL",
  "SIGNOPUNTO",
  "SIGNOPOR",
  "SIGNOMAS",
  "SIGNOMENOS",
  "SIGNODIVISION",
  "SIGNOAND",
  "SIGNOOR",
  "SIGNONOT",
  "SIGNOIGUAL",
  "SIGNOCOMA",
  "SIGNODIFERENTE",
  "SIGNOINCREMENTO",
  "DOLAR",
  "RESERVADA_INT",
  "RESERVADA_DOUBLE",
  "RESERVADA_CHAR",
  "RESERVADA_BOOL",
  "RESERVADA_TRUE",
  "RESERVADA_FALSE",
  "RESERVADA_STRING",
  "RESERVADA_VOID",
  "RESERVADA_MAIN",
  "RESERVADA_IF",
  "RESERVADA_CONSOLE",
  "RESERVADA_WRITE",
  "RESERVADA_ELSE",
  "RESERVADA_DEFINIRG",
  "RESERVADA_FOR",
  "RESERVADA_WHILE",
  "RESERVADA_BREAK",
  "RESERVADA_NEWVALOR",
  "RESERVADA_GRAFICARBARRAS",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "RESERVADA_TITULOX",
  "RESERVADA_TITULOY",
  "RESERVADA_TITULO",
  "ENTERO",
  "ID",
  "DECIMALES",
  "CHARR",
  "CADENA",
  "RESERVADA_VALORES",
  "RESERVADA_EJEX",
  "RESERVADA_DO",
  "RESERVADA_SWITCH",
  "DOSPUNTOS",
  "RESERVADA_CASE",
  "RESERVADA_DEFAULT",
  "RESERVADA_GRAFICARPIE"
  };
}

