
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizarxd;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEABRE = 7;
  public static final int DOSPUNTOS = 11;
  public static final int PUNTOYCOMA = 12;
  public static final int PARENTESISCIERRA = 10;
  public static final int ENTERO = 2;
  public static final int VIRGULILLA = 16;
  public static final int MAYORQUE = 15;
  public static final int PARENTESISABRE = 9;
  public static final int OR = 19;
  public static final int GUION = 13;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 14;
  public static final int CADENA = 4;
  public static final int RESERVADA_CONJ = 6;
  public static final int UNA_O_MUCHAS_VECES = 21;
  public static final int OPERACIONES = 5;
  public static final int GUION_BAJO = 20;
  public static final int PUNTO = 17;
  public static final int CORCHETECIERRA = 8;
  public static final int UNA_O_NINGUNA_VEZ = 22;
  public static final int CERO_O_MUCHAS_VECES = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "ID",
  "CADENA",
  "OPERACIONES",
  "RESERVADA_CONJ",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "GUION",
  "COMA",
  "MAYORQUE",
  "VIRGULILLA",
  "PUNTO",
  "CERO_O_MUCHAS_VECES",
  "OR",
  "GUION_BAJO",
  "UNA_O_MUCHAS_VECES",
  "UNA_O_NINGUNA_VEZ"
  };
}

