
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parc = 10;
  public static final int comilla = 17;
  public static final int dobleporc = 2;
  public static final int para = 9;
  public static final int cadena = 15;
  public static final int coma = 26;
  public static final int numero = 14;
  public static final int guion_bajo = 27;
  public static final int salto = 19;
  public static final int por = 4;
  public static final int porcent = 30;
  public static final int rango = 24;
  public static final int or = 8;
  public static final int question = 25;
  public static final int guion = 22;
  public static final int admiracion = 28;
  public static final int ma_que = 23;
  public static final int igual = 3;
  public static final int EOF = 0;
  public static final int pr_er = 13;
  public static final int id = 16;
  public static final int simple = 18;
  public static final int error = 1;
  public static final int pr_conj = 20;
  public static final int mas = 5;
  public static final int llavec = 12;
  public static final int dos_ptn = 21;
  public static final int pnt_coma = 7;
  public static final int llavea = 11;
  public static final int pnt = 6;
  public static final int and = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dobleporc",
  "igual",
  "por",
  "mas",
  "pnt",
  "pnt_coma",
  "or",
  "para",
  "parc",
  "llavea",
  "llavec",
  "pr_er",
  "numero",
  "cadena",
  "id",
  "comilla",
  "simple",
  "salto",
  "pr_conj",
  "dos_ptn",
  "guion",
  "ma_que",
  "rango",
  "question",
  "coma",
  "guion_bajo",
  "admiracion",
  "and",
  "porcent"
  };
}

